const tcp_protocol_controller = require("./src/protocols/tcp");
console.log(process.memoryUsage())
tcp_protocol_controller([{ port: 2000, host: 'localhost', name: 'server1' }, { port: 3000, host: 'localhost', name: "2344" }], false, (req, res) => {
    // console.log(req)
    // console.log(process.memoryUsage())

    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")

    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")


    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
    res.send({ "ode": 'martins' })
    res.send({ "ode": 'martins' }, "2344")
}).on('TCP_ERR_CONN', (err) => {
    // console.log(err)
}).on("SERV_CONN", (data) => {
    // console.log(data.clientID)
})

process.on('SIGINT', () => {
    console.log(process.memoryUsage())
    process.exit()
})